#!/usr/bin/env python3
"""
Docling PDF Image Extractor - Command Line Interface

A comprehensive CLI tool for extracting images and tables from PDF documents using Docling,
with the same functionality as the GUI version but optimized for command-line usage and automation.

Features:
- PDF file input with validation
- Configurable output directory
- Page range selection (start/end pages)
- Image processing options (generate pictures, scale, classification)
- Processing enrichments (code, formula)
- Table processing options (images, structure, cell matching)
- Accelerator options (threads, device selection)
- Comprehensive logging and error handling
- Progress reporting
- Cross-platform compatibility

Usage Examples:
    Basic usage:
        python docling_basic_parse_cli.py input.pdf

    Specify output directory:
        python docling_basic_parse_cli.py input.pdf -o output_folder

    Process specific page range:
        python docling_basic_parse_cli.py input.pdf --start-page 5 --end-page 10

    Advanced configuration:
        python docling_basic_parse_cli.py input.pdf \\
            --output-dir custom_output \\
            --start-page 1 --end-page 20 \\
            --no-pictures --images-scale 3.0 \\
            --code-enrichment --formula-enrichment \\
            --table-images --table-structure \\
            --threads 4 --device CPU \\
            --verbose

    Batch processing with custom settings:
        python docling_basic_parse_cli.py document.pdf \\
            --output-dir processed_docs \\
            --start-page 1 --end-page 50 \\
            --generate-pictures --images-scale 2.0 \\
            --picture-classification \\
            --generate-table-images --table-structure --cell-matching \\
            --threads 8 --device CUDA \\
            --log-level DEBUG

Author: Generated by code-supernova
License: MIT
"""

import os
import sys
import argparse
import logging
from pathlib import Path
from typing import Optional, Tuple, List
import traceback

# Docling imports
from docling.document_converter import DocumentConverter, PdfFormatOption
from docling.datamodel.accelerator_options import AcceleratorDevice, AcceleratorOptions
from docling.datamodel.pipeline_options import PdfPipelineOptions, granite_picture_description
from docling.datamodel.base_models import InputFormat
from docling_core.types.doc.base import ImageRefMode
from docling.datamodel.settings import settings

# Import the existing image extraction function
from docling_basic_parse import extract_images_and_modify_markdown


class DoclingCLIError(Exception):
    """Custom exception for Docling CLI errors."""
    pass


class ConfigurationError(DoclingCLIError):
    """Exception raised for configuration validation errors."""
    pass


class ProcessingError(DoclingCLIError):
    """Exception raised for PDF processing errors."""
    pass


class DoclingCLI:
    """
    Main CLI class for Docling PDF Image Extractor.

    Handles argument parsing, configuration validation, logging setup,
    and orchestrates the PDF processing pipeline.
    """

    def __init__(self, args=None):
        """Initialize the Docling CLI with argument parsing and configuration."""
        self.logger = None
        self.args = None
        self._setup_logging()
        if args is None:
            self._parse_arguments()
        else:
            self.args = args

    def _setup_logging(self) -> None:
        """Set up logging configuration with multiple levels and formats."""
        self.logger = logging.getLogger('docling_cli')
        self.logger.setLevel(logging.DEBUG)

        # Remove existing handlers to avoid duplicates
        self.logger.handlers.clear()

        # Console handler with custom formatter
        console_handler = logging.StreamHandler(sys.stdout)
        console_handler.setLevel(logging.INFO)

        # Detailed formatter for console output
        formatter = logging.Formatter(
            '%(asctime)s - %(name)s - %(levelname)s - %(message)s',
            datefmt='%H:%M:%S'
        )
        console_handler.setFormatter(formatter)
        self.logger.addHandler(console_handler)

    def _parse_arguments(self) -> None:
        """Parse command line arguments with comprehensive validation."""
        parser = argparse.ArgumentParser(
            prog='docling_basic_parse_cli',
            description='Extract images and tables from PDF documents using Docling',
            formatter_class=argparse.RawDescriptionHelpFormatter,
            epilog="""
Examples:
  python docling_basic_parse_cli.py document.pdf
  python docling_basic_parse_cli.py input.pdf -o output_folder --start-page 5 --end-page 10
  python docling_basic_parse_cli.py doc.pdf --threads 8 --device CUDA --verbose
            """
        )

        # Required arguments
        parser.add_argument(
            'input_file',
            help='Path to the input PDF file'
        )

        # Output configuration
        parser.add_argument(
            '-o', '--output-dir',
            help='Output directory for extracted images and markdown (default: images_<input_filename>)'
        )

        # Page range options
        parser.add_argument(
            '--start-page',
            type=int,
            default=1,
            help='Starting page number for processing (default: 1)'
        )
        parser.add_argument(
            '--end-page',
            type=int,
            default=None,
            help='Ending page number for processing (default: last page of document)'
        )

        # Image processing options
        parser.add_argument(
            '--generate-pictures',
            action='store_true',
            default=True,
            help='Generate picture images from PDF (default: True)'
        )
        parser.add_argument(
            '--no-pictures',
            action='store_true',
            help='Disable picture image generation'
        )
        parser.add_argument(
            '--images-scale',
            type=float,
            default=2.0,
            help='Scale factor for generated images (default: 2.0)'
        )
        parser.add_argument(
            '--picture-classification',
            action='store_true',
            default=False,
            help='Enable picture classification (default: False)'
        )

        # Enrichment options
        parser.add_argument(
            '--code-enrichment',
            action='store_true',
            default=True,
            help='Enable code syntax enrichment (default: True)'
        )
        parser.add_argument(
            '--formula-enrichment',
            action='store_true',
            default=True,
            help='Enable mathematical formula enrichment (default: True)'
        )
        # Table processing options
        parser.add_argument(
            '--table-images',
            action='store_true',
            default=True,
            help='Generate table images (default: True)'
        )
        parser.add_argument(
            '--table-structure',
            action='store_true',
            default=True,
            help='Enable table structure recognition (default: True)'
        )
        parser.add_argument(
            '--cell-matching',
            action='store_true',
            default=True,
            help='Enable cell matching for tables (default: True)'
        )


        # Accelerator options
        parser.add_argument(
            '--threads',
            type=int,
            default=8,
            help='Number of processing threads (default: 8)'
        )
        parser.add_argument(
            '--device',
            choices=['CPU', 'CUDA'],
            default='CUDA',
            help='Processing device: CPU or CUDA (default: CUDA)'
        )

        # Logging and verbosity
        parser.add_argument(
            '-v', '--verbose',
            action='store_true',
            help='Enable verbose logging (INFO level)'
        )
        parser.add_argument(
            '--debug',
            action='store_true',
            help='Enable debug logging (DEBUG level)'
        )
        parser.add_argument(
            '--quiet',
            action='store_true',
            help='Enable quiet mode (ERROR level only)'
        )

        # Output options
        parser.add_argument(
            '--output-markdown',
            help='Custom filename for output markdown file (default: <input_filename>_with_images.md)'
        )
        parser.add_argument(
            '--dry-run',
            action='store_true',
            help='Show configuration and exit without processing'
        )

        self.args = parser.parse_args()

        # Handle mutually exclusive options
        if self.args.no_pictures:
            self.args.generate_pictures = False

    def _configure_logging_level(self) -> None:
        """Configure logging level based on command line arguments."""
        if self.args.debug:
            logging.getLogger().setLevel(logging.DEBUG)
            for handler in self.logger.handlers:
                handler.setLevel(logging.DEBUG)
        elif self.args.verbose:
            logging.getLogger().setLevel(logging.INFO)
            for handler in self.logger.handlers:
                handler.setLevel(logging.INFO)
        elif self.args.quiet:
            logging.getLogger().setLevel(logging.ERROR)
            for handler in self.logger.handlers:
                handler.setLevel(logging.ERROR)
        else:
            # Default to WARNING level
            logging.getLogger().setLevel(logging.WARNING)
            for handler in self.logger.handlers:
                handler.setLevel(logging.WARNING)

    def _validate_configuration(self) -> None:
        """Validate the parsed configuration and raise appropriate errors."""
        # Validate input file
        if not os.path.exists(self.args.input_file):
            raise ConfigurationError(f"Input file does not exist: {self.args.input_file}")

        if not self.args.input_file.lower().endswith('.pdf'):
            raise ConfigurationError(f"Input file must be a PDF: {self.args.input_file}")

        # Validate page range
        if self.args.start_page < 1:
            raise ConfigurationError("Start page must be greater than 0")

        if self.args.end_page is not None and self.args.end_page < self.args.start_page:
            raise ConfigurationError("End page must be greater than or equal to start page")

        # Validate threads
        if self.args.threads < 1:
            raise ConfigurationError("Number of threads must be greater than 0")

        # Validate image scale
        if self.args.images_scale <= 0:
            raise ConfigurationError("Image scale must be greater than 0")

        # Validate output directory
        if self.args.output_dir:
            output_path = Path(self.args.output_dir)
            if output_path.is_file():
                raise ConfigurationError(f"Output path exists and is a file: {self.args.output_dir}")

        self.logger.info("Configuration validation completed successfully")

    def _get_output_paths(self) -> Tuple[str, str]:
        """Generate output directory and markdown filename."""
        input_path = Path(self.args.input_file)

        # Determine output directory
        if self.args.output_dir:
            output_dir = self.args.output_dir
        else:
            output_dir = f"images_{input_path.stem}"

        # Determine markdown filename
        if self.args.output_markdown:
            markdown_file = self.args.output_markdown
        else:
            markdown_file = f"{input_path.stem}_with_images.md"

        return output_dir, markdown_file

    def _create_pipeline_options(self) -> PdfPipelineOptions:
        """Create and configure PDF pipeline options based on CLI arguments."""
        pipeline_options = PdfPipelineOptions()

        # Image options
        pipeline_options.generate_picture_images = self.args.generate_pictures
        pipeline_options.images_scale = self.args.images_scale
        pipeline_options.do_picture_classification = self.args.picture_classification

        # Enrichment options
        pipeline_options.do_code_enrichment = self.args.code_enrichment
        pipeline_options.do_formula_enrichment = self.args.formula_enrichment

        # Set picture description options if classification is enabled
        if self.args.picture_classification:
            pipeline_options.picture_description_options = granite_picture_description

        # Table options
        pipeline_options.generate_table_images = self.args.table_images
        pipeline_options.do_table_structure = self.args.table_structure
        if hasattr(pipeline_options, 'table_structure_options') and self.args.table_structure:
            pipeline_options.table_structure_options.do_cell_matching = self.args.cell_matching

        # Accelerator options
        accelerator_options = AcceleratorOptions(
            num_threads=self.args.threads,
            device=AcceleratorDevice.CUDA if self.args.device == "CUDA" else AcceleratorDevice.CPU
        )
        pipeline_options.accelerator_options = accelerator_options

        return pipeline_options

    def _log_configuration(self) -> None:
        """Log the current configuration for user reference."""
        self.logger.info("=== Docling CLI Configuration ===")
        self.logger.info(f"Input file: {self.args.input_file}")
        self.logger.info(f"Output directory: {self._get_output_paths()[0]}")
        self.logger.info(f"Output markdown: {self._get_output_paths()[1]}")
        self.logger.info(f"Page range: {self.args.start_page} - {self.args.end_page or 'end'}")
        self.logger.info(f"Generate pictures: {self.args.generate_pictures}")
        self.logger.info(f"Image scale: {self.args.images_scale}")
        self.logger.info(f"Picture classification: {self.args.picture_classification}")
        self.logger.info(f"Code enrichment: {self.args.code_enrichment}")
        self.logger.info(f"Formula enrichment: {self.args.formula_enrichment}")
        self.logger.info(f"Table images: {self.args.table_images}")
        self.logger.info(f"Table structure: {self.args.table_structure}")
        self.logger.info(f"Cell matching: {self.args.cell_matching}")
        self.logger.info(f"Threads: {self.args.threads}")
        self.logger.info(f"Device: {self.args.device}")
        self.logger.info("=" * 35)

    def run(self) -> int:
        """
        Main execution method for the CLI tool.

        Returns:
            int: Exit code (0 for success, 1 for error)
        """
        try:
            # Configure logging level
            self._configure_logging_level()

            # Validate configuration
            self._validate_configuration()

            # Print current selected options
            print("\nSelected Options:")
            print("=" * 50)
            print(f"Input File:             {self.args.input_file}")
            print(f"Output Directory:       {self._get_output_paths()[0]}")
            print(f"Page Range:             {self.args.start_page} - {self.args.end_page or 'end'}")
            print(f"Generate Pictures:      {self.args.generate_pictures}")
            print(f"Image Scale:           {self.args.images_scale}x")
            print(f"Picture Classification: {self.args.picture_classification}")
            print(f"Code Enrichment:       {self.args.code_enrichment}")
            print(f"Formula Enrichment:    {self.args.formula_enrichment}")
            print(f"Table Images:          {self.args.table_images}")
            print(f"Table Structure:       {self.args.table_structure}")
            print(f"Cell Matching:         {self.args.cell_matching}")
            print(f"Processing Threads:    {self.args.threads}")
            print(f"Processing Device:     {self.args.device}")
            print("=" * 50)
            print()

            # Log configuration in dry run mode
            if self.args.dry_run:
                self._log_configuration()
                self.logger.info("Dry run completed - no processing performed")
                return 0

            # Log configuration
            self._log_configuration()

            # Get output paths
            output_dir, markdown_file = self._get_output_paths()

            self.logger.info("Starting PDF processing...")

            # Create output directory if it doesn't exist
            os.makedirs(output_dir, exist_ok=True)

            # Determine page range for processing
            # Handle None end_page properly for Docling converter
            if self.args.end_page is not None:
                page_range = (self.args.start_page, self.args.end_page)
            else:
                # Don't pass page_range at all if end_page is None to avoid Docling validation error
                page_range = None

            # Use the existing extraction function
            self.logger.info("Converting PDF document and extracting images...")

            # Add debugging for the conversion process
            self.logger.debug(f"Input file: {self.args.input_file}")
            self.logger.debug(f"Output folder: {output_dir}")
            self.logger.debug(f"Page range: {page_range}")

            try:
                modified_markdown, saved_images, saved_tables = extract_images_and_modify_markdown(
                    source_path=self.args.input_file,
                    output_folder=output_dir,
                    page_range=page_range
                )
            except Exception as e:
                self.logger.error(f"Error in extract_images_and_modify_markdown: {e}")
                self.logger.error(f"Error type: {type(e)}")
                import traceback
                self.logger.error(f"Traceback: {traceback.format_exc()}")
                raise

            # Save the modified markdown
            self.logger.info(f"Saving markdown to: {markdown_file}")
            with open(markdown_file, "w", encoding="utf-8") as f:
                f.write(modified_markdown)

            # Log results
            extracted_images = len([img for img in saved_images if img])
            extracted_tables = len([tbl for tbl in saved_tables if tbl])

            self.logger.info("=== Processing completed successfully! ===")
            self.logger.info(f"Extracted images: {extracted_images}")
            self.logger.info(f"Extracted tables: {extracted_tables}")
            self.logger.info(f"Markdown file: {markdown_file}")
            self.logger.info(f"Images directory: {output_dir}")
            self.logger.info("=" * 40)

            return 0

        except ConfigurationError as e:
            self.logger.error(f"Configuration error: {e}")
            return 1
        except ProcessingError as e:
            self.logger.error(f"Processing error: {e}")
            return 1
        except Exception as e:
            self.logger.error(f"Unexpected error: {e}")
            self.logger.debug(f"Traceback: {traceback.format_exc()}")
            return 1


def main() -> int:
    """
    Main entry point for the CLI application.

    Returns:
        int: Exit code
    """
    try:
        cli = DoclingCLI()
        return cli.run()
    except KeyboardInterrupt:
        print("\nOperation cancelled by user")
        return 130
    except Exception as e:
        print(f"Fatal error: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    exit_code = main()
    sys.exit(exit_code)